WKMap("ct", "<cmd>RustLsp testables<CR>", "testables")
WKMap("cT", "<cmd>RustLsp test<CR>", "test")
WKMap("cr", "<cmd>RustLsp runnables<CR>", "runnables")
WKMap("cR", "<cmd>RustLsp run<CR>", "run")
WKMap("cd", "<cmd>RustLsp debuggables<CR>", "debuggables")
WKMap("cD", "<cmd>RustLsp debug<CR>", "debug")
WKMap("ce", "<cmd>RustLsp expandMacro<CR>", "expand macro")
WKMap("ca", "<cmd>RustLsp codeAction<CR>", "code actions")
WKMap("cH", "<cmd>RustLsp hover actions<CR>", "hover actions")
WKMap("de", "<cmd>RustLsp explainError<CR>", "explain error")
WKMap("dr", "<cmd>RustLsp renderDiagnostic<CR>", "render diagnostic")
WKMap("dR", "<cmd>RustLsp relatedDiagnostics<CR>", "related diagnostic")
WKMap("Hd", "<cmd>RustLsp openDocs<CR>", "open docs at cursor")
