local U = require("adudenamedruby.core.utils")

U.GLMap("ct", "<cmd>RustLsp testables<CR>", "testables")
U.GLMap("cT", "<cmd>RustLsp test<CR>", "test")
U.GLMap("cr", "<cmd>RustLsp runnables<CR>", "runnables")
U.GLMap("cR", "<cmd>RustLsp run<CR>", "run")
U.GLMap("cd", "<cmd>RustLsp debuggables<CR>", "debuggables")
U.GLMap("cD", "<cmd>RustLsp debug<CR>", "debug")
U.GLMap("ce", "<cmd>RustLsp expandMacro<CR>", "expand macro")
-- U.GLMap("ca", "<cmd>RustLsp codeAction<CR>", "code actions")
U.GLMap("cH", "<cmd>RustLsp hover actions<CR>", "hover actions")
U.GLMap("de", "<cmd>RustLsp explainError<CR>", "explain error")
U.GLMap("dr", "<cmd>RustLsp renderDiagnostic<CR>", "render diagnostic")
U.GLMap("dR", "<cmd>RustLsp relatedDiagnostics<CR>", "related diagnostic")
U.GLMap("Hd", "<cmd>RustLsp openDocs<CR>", "open docs at cursor")
