(require 'synthmacs-general)
(require 'synthmacs-evil)
(require 'synthmacs-general-keybindings)
(require 'synthmacs-winum)
(require 'synthmacs-vertico)
(require 'synthmacs-orderless)
(require 'synthmacs-consult)
(require 'synthmacs-marginalia)
(require 'synthmacs-embark)
(require 'synthmacs-icons)
(require 'synthmacs-modeline)
(require 'synthmacs-themes)
(require 'synthmacs-hydra)
(require 'synthmacs-which-key)
(require 'synthmacs-rainbow)
(require 'synthmacs-helpful)
(require 'synthmacs-rg)
(require 'synthmacs-projectile)
(require 'synthmacs-magit)
(require 'synthmacs-dashboard)
;; (require 'synthmacs-obsidian)
(require 'synthmacs-avy)

(provide 'synthmacs-packages)
