(require 'treesit)
(setq treesit-language-source-alist
   '((bash "https://github.com/tree-sitter/tree-sitter-bash")
     (c "https://github.com/tree-sitter/tree-sitter-c")
     (cmake "https://github.com/uyha/tree-sitter-cmake")
     (clojure "https://github.com/sogaiu/tree-sitter-clojure")
     (commonlisp "https://github.com/theHamsta/tree-sitter-commonlisp")
     (css "https://github.com/tree-sitter/tree-sitter-css")
     (elixir "https://github.com/elixir-lang/tree-sitter-elixir")
     (elisp "https://github.com/Wilfred/tree-sitter-elisp")
     (go "https://github.com/tree-sitter/tree-sitter-go")
     (html "https://github.com/tree-sitter/tree-sitter-html")
     (haskell "https://github.com/tree-sitter/tree-sitter-haskell")
     (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
     (json "https://github.com/tree-sitter/tree-sitter-json")
     (lua "https://github.com/Azganoth/tree-sitter-lua")
     (make "https://github.com/alemuller/tree-sitter-make")
     (markdown "https://github.com/ikatyang/tree-sitter-markdown")
     (objc "https://github.com/jiyee/tree-sitter-objc")
     (ocaml "https://github.com/tree-sitter/tree-sitter-ocaml")
     (python "https://github.com/tree-sitter/tree-sitter-python")
     (racket "https://github.com/6cdh/tree-sitter-racket")
     (ruby "https://github.com/tree-sitter/tree-sitter-ruby")
     (rust "https://github.com/tree-sitter/tree-sitter-rust")
     (scheme "https://github.com/6cdh/tree-sitter-scheme")
     (sqlite "https://github.com/dhcmrlchtdj/tree-sitter-sqlite")
     (sql "https://github.com/m-novikov/tree-sitter-sql")
     (swift "https://github.com/alex-pinkus/tree-sitter-swift")
     (toml "https://github.com/tree-sitter/tree-sitter-toml")
     (yaml "https://github.com/ikatyang/tree-sitter-yaml")
     (zig "https://github.com/maxxnino/tree-sitter-zig")))



(add-to-list 'major-mode-remap-alist
	     '(c-mode . c-ts-mode)
	     '(sh-mode . bash-ts-mode))


(provide 'synthmacs-treesitter)
