return {
    -- "kevinhwang91/nvim-ufo",
    -- dependencies = "kevinhwang91/promise-async",
    -- config = function()
    --     vim.o.foldcolumn = "1" -- '0' is not bad
    --     vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
    --     vim.o.foldlevelstart = 99
    --     vim.o.foldenable = true
    --
    --     KMap("zR", require("ufo").openAllFolds, "open all folds")
    --     KMap("zM", require("ufo").closeAllFolds, "close all folds")
    --     KMap("zK", function()
    --         local winid = require("ufo").peekFoldedLinesUnderCursor()
    --         if not winid then
    --             vim.lsp.buf.hover()
    --         end
    --     end, "peek Fold")
    --
    --     require("ufo").setup({
    --         provider_selector = function(bufnr, filetype, buftype)
    --             return { "treesitter", "indent" }
    --             -- return { "lsp", "indent" }
    --         end,
    --     })
    -- end,
}
